Async iterator pagination
architect/aws-lite pull request #157
Opened 2024-06-29 22:36 UTC by aspilchen

## Thank you for helping out! ✨

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `master`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

2024-06-29 22:38 UTC, aspilchen commented
TODO: handle errors and create tests

2024-07-03 20:30 UTC, aspilchen reviewed
https://github.com/architect/aws-lite/blob/bebf88c949666d8c14745fbab657738b0b818106/src/request/index.js#L268 

Throws error if `params[type]` does not exist

2024-07-04 16:03 UTC, ryanblock requested changes

2024-07-04 16:03 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +  t.equal(request.url, expectedUrl, 'Response token does not match next request cursor')
All of these tests notate "incorrect..." or "does not match..." when a passing test would be correct, or match, etc. As a reminder, the third argument in most of these `tape` methods is the description of the test in question.

2024-07-04 16:03 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +  t.true(page.done, 'Iterator not done when it ought to be')
Prefer `t.ok`

2024-07-04 16:07 UTC, ryanblock commented
> https://github.com/architect/aws-lite/blob/bebf88c949666d8c14745fbab657738b0b818106/src/request/index.js#L268
> 
> Throws error if `params[type]` does not exist

Got it, interesting this hasn't come up, but that's why unit tests are nice. :)

I'm thinking if `params[type]` then perhaps we need to backfill it earlier in execution, like `params[type] = params[type] || {}`?

2024-07-10 15:46 UTC, ryanblock requested changes

2024-07-10 15:46 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +    server.use({ responseGenerator })
Any particular reason not to do `server.use({ accumulateRequests: true, responseGenerator })`?

2024-07-10 15:46 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +    t.equal(requests.length, simpleResponses.length, 'Server does not send extra request')
Did you mean 'Client does not send extra request'?

2024-07-10 15:46 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +    expectedResponsePayload = { Accumulator: [ 'a1', 'a2', 'a3' ] }
Instead of hardcoding these, I'd suggest referring to the actual data in question.

2024-07-10 15:46 UTC, ryanblock commented on test/unit/src/index-paginator-test.mjs
> +test('Default paginator - plugin', async t => {
I think we should bail on using a production plugin for this test case, and replicate the use case with a stripped down custom plugin, as we do in other tests (e.g. https://github.com/architect/aws-lite/blob/main/test/unit/src/index-plugins-test.mjs).

2024-07-19 20:57 UTC, merged